site_name: DocumentDB
repo_url: https://github.com/microsoft/documentdb
theme:
  name: readthedocs

nav:
  - Version 1.0:
      - Get Started: v1/index.md
      - Introduction: v1/documentdb.md
      - Prebuild Images: v1/prebuild.md
      - Gateway: v1/gateway.md

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
