name: DocumentDB sql tests
run-name: ${{ github.event.pull_request.title || '' }}
concurrency:
  group: sql-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'docs/**'
      - '.devcontainer/**'
      - '*.md'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths-ignore:
      - 'docs/**'
      - '.devcontainer/**'
      - '*.md'

jobs:
  test-pr:
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        include:
          - pg_version: 15
            arch: amd64
            runner: ubuntu-22.04
          - pg_version: 16
            arch: arm64
            runner: ubuntu-22.04-arm
          - pg_version: 17
            arch: amd64
            runner: ubuntu-22.04
    uses: ./.github/workflows/regress_tests_template.yml
    with:
      pg_version: ${{ matrix.pg_version }}
      arch: ${{ matrix.arch }}
      runner: ${{ matrix.runner }}

  test-full:
    if: github.event_name != 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        pg_version:
          - 15
          - 16
          - 17
        arch:
          - amd64
          - arm64
        include:
          - arch: amd64
            runner: ubuntu-22.04
          - arch: arm64
            runner: ubuntu-22.04-arm
    uses: ./.github/workflows/regress_tests_template.yml
    with:
      pg_version: ${{ matrix.pg_version }}
      arch: ${{ matrix.arch }}
      runner: ${{ matrix.runner }}

